import z from "zod";
export const CountryListSchema = z.enum([
  "Albania",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Belgium",
  "Bolivia",
  "BosniaHerzegovina",
  "Brazil",
  "Bulgaria",
  "Canada",
  "Chile",
  "China",
  "Croatia",
  "Cyprus",
  "CzechRepublic",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Hungary",
  "Israel",
  "Italy",
  "Kazakhstan",
  "Latvia",
  "Lebanon",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Mexico",
  "Moldova",
  "Montenegro",
  "Morocco",
  "Namibia",
  "Netherlands",
  "NewZealand",
  "NorthernMacedonia",
  "Peru",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "SouthAfrica",
  "Spain",
  "Sweden",
  "Switzerland",
  "Thailand",
  "Turkey",
  "Ukraine",
  "UnitedKingdom",
  "Uruguay",
  "USA",
  "Uzbekistan",
  "Vietnam",
]);

export const addressSchema = z.object({
  street: z.string(),
  city: z.string(),
  flat: z.string().optional().nullable(),
  address: z.string(),
  is_contact_address: z.boolean(),
  postcode: z.string().optional().nullable(),
  country: CountryListSchema.nullable(),
});



export type IAddress = z.infer<typeof addressSchema>;
